FROM caddy:2.11.4-builder AS builder

ARG GOPROXY=https://proxy.golang.org,direct

RUN xcaddy build --with github.com/corazawaf/coraza-caddy/v2@v2.5.0 \
  --with github.com/mholt/caddy-ratelimit@5625512f24f6f59d6f64fb3aafe5eecff0b286db

FROM caddy:2.11.4-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

RUN addgroup -S -g 1000 waf \
  && adduser -S -D -H -u 1000 -G waf waf \
  && mkdir -p /data /config \
  && chown -R waf:waf /data /config

USER 1000:1000
